


# SEO kit will honor the following
# title:   this would override the document's <title> suffix, defaults to name
# description:
# url:
# author:
# google_site_verification:
# logo:


google_site_verification: FZoDU79BdIo92Bmm-y8w7msNuiqSB7uENwumXr77zIs

name: "Fluid Thinking"

# compatibility
email: sam.briesemeister+blog@gmail.com

description: >
  Blog of Sam Briesemeister;
  advancing strategic business agility with DevOps in the evolving world of
  tech. On Software, Continuous Delivery, Business Intelligence, Analytics,
  Technology, Ethics, Information Security, Politics, and life in general.

url: "http://samb.io"  # no trailing slash
baseurl: ""  # empty, else we duplicate slashes.
permalink: /blog/:year/:categories/:slug

author:
  name: Sam Briesemeister
  email: sam.briesemeister+blog@gmail.com
  uri: http://samb.io/about
  twitter: systemalias
  github: samba
  linkedin: sambriesemeister

kontactr:
  id: 203667

# These for compatibility
twitter_username: systemalias
github_username: samba

github:
  username: samba

twitter:
  username: systemalias


# These settings for display widgets
twitter_feed:
  username: systemalias
  consumer_key: l92HsrzAmSpPRUtNoyLVcGEH#X
  consumer_secret: qFQIfa71zs5PRntOe5fK1EIqF8xWWMeGZnJu2kbdk6p23qmze#D

github: [metadata]

markdown: kramdown

highlighter: rouge


kramdown:
  input: GFM
  hard_wrap: false
  tables: true
  autolink: true
  auto_ids: true
  syntax_highlighter: rouge
  parse_block_html: true
  parse_span_html: true


rouge:
  css_class: "codehilite"
  scope: ".codehilite"


# assets:
#   prefix: "/assets"
#   sources:
#     - assets/css
#     - assets/images
#     - assets/javascripts
#     - assets/stylesheets
#     - assets/fonts
#     - assets/img
#     - assets/shim
#   digest: true
#   assets:
#     - '*.png'
#     - '*.jpg'
#     - 'bundle.css'
#   features:
#     liquid: true



gems:
  - kramdown
  - rouge
  - sass
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-mentions
  - jekyll-paginate
  - jekyll-seo-tag
  - jekyll-redirect-from



exclude:
  - node_modules
  - Dockerfile
  - Gemfile
  - Makefile
  - scripts