baseurl: /
permalink: /blog/:year/:categories/:title

# SEO kit will honor the following
# title:
# description:
# url:
# author:
# google_site_verification:
# logo:
#
name: "Think Big, Start Small"

description: "Blog of Sam Briesemeister; advancing strategic business agility with continuous delivery in the evolving world of tech. On Software, DevOps, Business Intelligence, Analytics, Continuous Delivery, Technology, Ethics, Information Security, Politics, and life in general."

author:
  name: Sam Briesemeister
  email: sam.briesemeister+blog@gmail.com
  uri: http://samba.github.io/about
  twitter: systemalias

twitter:
  username: systemalias


github: [metadata]


markdown: kramdown

highlighter: rouge


kramdown:
  input: GFM
  hard_wrap: false
  tables: true
  autolink: true
  auto_ids: true
  syntax_highlighter: rouge

rouge:
  css_class: "codehilite"
  scope: ".codehilite"

gems:
  - kramdown
  - rouge
  - sass
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-mentions
  - jekyll-paginate
  - jekyll-seo-tag
  - jekyll-redirect-from


exclude:
  - node_modules
  - Dockerfile
  - Gemfile
  - Makefile
  - scripts