baseurl: /

params:
  title: "Blog of Sam Briesemeister"
  description: "Advancing business capability and agility with a product paradigm and continuous delivery principles."

github: [metadata]

permalink: /blog/:year/:categories/:title

markdown: kramdown

highlighter: rouge


kramdown:
  input: GFM
  hard_wrap: false
  tables: true
  autolink: true
  auto_ids: true
  syntax_highlighter: rouge

rouge:
  css_class: "codehilite"
  scope: ".codehilite"

gems:
  - kramdown
  - rouge
  - sass

exclude:
  - node_modules
  - Dockerfile
  - Gemfile
  - Makefile
  - scripts